#schéma yml
version: 2


sources:
  - name: raw
    schema: gz_raw_data
    description: donnée brut de Greenweez
    tables:
      - name: raw_gz_sales
        identifier: sales
        description: données de ventes

      - name: raw_gz_ship
        identifier: ship
        description: données de shipment

      - name: raw_gz_products
        identifier: products
        description: données sur les produits