#schéma yml
version: 2


sources:
  - name: raw
    schema: gz_raw_data
    description: donnée brut de Greenweez
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: données de ventes

      - name: ship
        identifier: raw_gz_ship
        description: données de shipment

      - name: product
        identifier: raw_gz_product  
        description: données sur les produits